name: mlflow_env
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=0.9.5
  - appdirs=1.4.4
  - asn1crypto=1.4.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - configparser=5.0.2
  - cryptography=3.4.7
  - databricks-cli=0.9.1
  - docker-py=5.0.0
  - docker-pycreds=0.4.0
  - entrypoints=0.3
  - flask=1.1.2
  - gitdb=4.0.7
  - gitpython=3.1.15
  - greenlet=1.0.0
  - gunicorn=20.1.0
  - idna=2.10
  - importlib-metadata=4.0.1
  - itsdangerous=1.1.0
  - jinja2=2.11.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.1.0
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libprotobuf=3.15.8
  - llvm-openmp=11.1.0
  - mako=1.1.4
  - markupsafe=1.1.1
  - mlflow=1.15.0
  - ncurses=6.2
  - numpy=1.19.5
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.1.5
  - pip=21.0.1
  - prometheus_client=0.10.1
  - prometheus_flask_exporter=0.18.1
  - protobuf=3.15.8
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python_abi=3.6
  - pytz=2021.1
  - pyyaml=5.4.1
  - querystring_parser=1.2.4
  - readline=8.1
  - requests=2.25.1
  - setuptools=49.6.0
  - six=1.15.0
  - smmap=3.0.5
  - sqlalchemy=1.4.11
  - sqlite=3.35.4
  - sqlparse=0.4.1
  - tabulate=0.8.9
  - tk=8.6.10
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.1
  - zlib=1.2.11
